name: Build Ren'Py APK
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: project
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v3
        id: cache-renpy
        with:
          path: renpy
          key: ${{ runner.os }}-renpy
      - uses: Ayowel/renpy-setup-action@v2.0.1
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        with:
          action: install
          install_dir: renpy
          dlc: rapt
          android_sdk: true
      - name: Build APK
        uses: Ayowel/renpy-setup-action@v2.0.1
        with:
          action: distribute
          install_dir: renpy
          game: project/game
          packages: android
          out_dir: project/bin
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: project/bin/*.apk
